generic-service:
  nameOverride: hmpps-person-communication-needs-api
  productId: "DPS013"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-person-communication-needs-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-person-communication-needs-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-person-communication-needs-api:
      CLIENT_ID: "CLIENT_ID"
      CLIENT_SECRET: "CLIENT_SECRET"

    digital-prison-reporting:
      DPR_USER: "dpr_user"
      DPR_PASSWORD: "dpr_password"

    hmpps-person-communication-needs-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-person-communication-needs-api
